---
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: ns1
  labels:
    app: demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: ns1
  labels:
    app: demo
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: v1
    spec:
      containers:
      - name: webserver
        image: ehazlett/docker-demo
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "v1"
        - name: METADATA
          value: "production"
